# Generated by Django 5.2.17 on 2026-09-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('width', models.FloatField(verbose_name='Breite (m)')),
                ('height', models.FloatField(verbose_name='Länge (m)')),
                ('location', models.OneToOneField(help_text='Ort, unter dem die Planobjekte als Unterorte angelegt werden.', on_delete=django.db.models.deletion.PROTECT, related_name='floor_plan', to='inventory.location', verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Hallenplan',
                'verbose_name_plural': 'Hallenpläne',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('area', 'Bereich / Raum'), ('cabinet', 'Schrank / Regal'), ('workstation', 'Tisch / Arbeitsplatz'), ('test_rig', 'Versuchsstand / Anlage'), ('marking', 'Markierung / Weg'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Art')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Beschriftung')),
                ('x', models.FloatField(verbose_name='x (m)')),
                ('y', models.FloatField(verbose_name='y (m)')),
                ('width', models.FloatField(verbose_name='Breite (m)')),
                ('height', models.FloatField(verbose_name='Tiefe (m)')),
                ('rotation', models.FloatField(default=0, verbose_name='Drehung (°)')),
                ('color', models.CharField(blank=True, help_text='z. B. #ffffff', max_length=7, verbose_name='Farbe')),
                ('z', models.IntegerField(default=0, verbose_name='Ebene')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_element', to='inventory.location', verbose_name='Ort')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='floorplan.floorplan', verbose_name='Hallenplan')),
            ],
            options={
                'verbose_name': 'Planobjekt',
                'verbose_name_plural': 'Planobjekte',
                'ordering': ['z', 'pk'],
            },
        ),
    ]
