# Generated by Django 5.2.17 on 2026-09-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_preferences(apps, schema_editor):
    """Einstellungen für bestehende Konten anlegen; abgeschaltete Erinnerungen übernehmen."""
    User = apps.get_model("accounts", "User")
    NotificationPreferences = apps.get_model("accounts", "NotificationPreferences")
    for user in User.objects.all():
        off = {} if user.email_reminders else {"start_reminder": -1, "due_reminder": -1, "pending_digest": -1}
        NotificationPreferences.objects.get_or_create(user=user, defaults=off)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Hauptschalter. Mahnungen zu überfälligen Rückgaben kommen trotzdem.', verbose_name='E-Mail-Benachrichtigungen')),
                ('booking_updates', models.BooleanField(default=True, help_text='Anfrage oder Verlängerung genehmigt/abgelehnt, Storno durch Verantwortliche, verfallene Anfragen und Reservierungen, für mich eingetragene Buchungen.', verbose_name='Neuigkeiten zu meinen Buchungen')),
                ('start_reminder', models.SmallIntegerField(choices=[(1, '1 Tag vorher'), (0, 'am Starttag'), (-1, 'keine Erinnerung')], default=1, verbose_name='Erinnerung: Reservierung beginnt')),
                ('due_reminder', models.SmallIntegerField(choices=[(2, '2 Tage vorher'), (1, '1 Tag vorher'), (0, 'am Rückgabetag'), (-1, 'keine Erinnerung')], default=1, verbose_name='Erinnerung: Rückgabe fällig')),
                ('overdue_interval', models.SmallIntegerField(choices=[(1, 'täglich'), (2, 'alle 2 Tage'), (7, 'wöchentlich')], default=2, help_text='Lässt sich nicht abschalten – andere warten vielleicht auf das Gerät.', verbose_name='Mahnung bei überfälliger Rückgabe')),
                ('item_available', models.BooleanField(default=True, help_text='Wenn ein Gerät zurückgegeben wurde und meine Reservierung bald beginnt.', verbose_name='Gerät ist wieder da')),
                ('new_requests', models.BooleanField(default=True, help_text='Sofort per E-Mail.', verbose_name='Neue Ausleih- und Verlängerungsanfragen')),
                ('pending_digest', models.SmallIntegerField(choices=[(1, 'nach 1 Tag'), (2, 'nach 2 Tagen'), (3, 'nach 3 Tagen'), (-1, 'keine Erinnerung')], default=2, verbose_name='Erinnerung an unbeantwortete Anfragen')),
                ('owner_returns', models.BooleanField(default=True, help_text='Rückgaben mit Hinweis (z. B. „Kabel fehlt“) kommen immer.', verbose_name='Rückgabe und Storno bei genehmigungspflichtigen Geräten')),
                ('owner_activity', models.BooleanField(default=False, help_text='Wenn jemand eines meiner frei entnehmbaren Geräte ausleiht, reserviert oder zurückgibt.', verbose_name='Aktivität an frei entnehmbaren Geräten')),
                ('owner_overdue', models.BooleanField(default=True, help_text='Am ersten Tag der Überfälligkeit, danach wöchentlich.', verbose_name='Mein Gerät ist überfällig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benachrichtigungseinstellungen',
                'verbose_name_plural': 'Benachrichtigungseinstellungen',
            },
        ),
        migrations.RunPython(create_preferences, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='email_reminders',
        ),
    ]
