# Generated by Django 5.2.17 on 2026-09-23 13:36

import django.db.models.deletion
import inventory.models
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('path', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Pfad')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='Übergeordnet')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Modell / Typ')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('inventory_number', models.CharField(blank=True, help_text='Offizielle Inventarnummer, falls vorhanden.', max_length=50, verbose_name='Inventarnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('location_note', models.CharField(blank=True, help_text='z. B. „oberstes Fach, blaue Kiste“', max_length=200, verbose_name='Ablagehinweis')),
                ('loan_policy', models.CharField(choices=[('free', 'Frei entnehmbar'), ('approval', 'Nur mit Genehmigung')], default='free', help_text='„Nur mit Genehmigung“: Andere müssen die Ausleihe anfragen und Sie entscheiden.', max_length=20, verbose_name='Ausleihregel')),
                ('condition', models.CharField(choices=[('ok', 'Einsatzbereit'), ('defect', 'Defekt'), ('repair', 'In Reparatur / Kalibrierung'), ('retired', 'Ausgemustert')], default='ok', max_length=20, verbose_name='Zustand')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Angelegt von')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_items', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlich')),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Anzahl')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='inventory.item', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Zubehörteil',
                'verbose_name_plural': 'Zubehör',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=inventory.models.photo_upload_to, verbose_name='Foto')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, upload_to=inventory.models.photo_upload_to, verbose_name='Vorschaubild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptfoto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.item', verbose_name='Gerät')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-is_primary', 'uploaded_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('path', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Pfad')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location', verbose_name='Übergeordnet')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
                'ordering': ['path'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.location', verbose_name='Ablageort'),
        ),
        migrations.CreateModel(
            name='ItemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('doc_type', models.CharField(choices=[('manual', 'Handbuch'), ('datasheet', 'Datenblatt'), ('calibration', 'Kalibrierschein'), ('software', 'Software'), ('other', 'Sonstiges')], default='manual', max_length=20, verbose_name='Art')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=inventory.models.document_upload_to, validators=[inventory.validators.validate_document_file], verbose_name='Datei')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.item', verbose_name='Gerät')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['doc_type', 'title', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file', ''), _negated=True), models.Q(('url', ''), _negated=True), _connector='OR'), name='document_has_file_or_url')],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_number', ''), _negated=True), fields=('inventory_number',), name='unique_inventory_number', violation_error_message='Diese Inventarnummer ist bereits vergeben.'),
        ),
    ]
