# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('unverified', 'Ungeprüft'), ('ok', 'Einsatzbereit'), ('defect', 'Defekt'), ('repair', 'In Reparatur / Kalibrierung'), ('retired', 'Ausgemustert')], default='ok', max_length=20, verbose_name='Zustand'),
        ),
    ]
