"""Kuratierte, eindeutig als einzelnes Gerät erkennbare Bestellungen."""

import re

CLEAR_DEVICE_NAMES = frozenset(
    [
        "CalPlus_Handmultimeter",
        "CalPlus_Netzgerät",
        "CalPlus_Oszilloskop",
        "KUKA_AgilusKR6",
        "Kübler_Magnetisches Messsystem",
        "Stäubli_TX200",
        "Zimmer_Greifer",
        "Schunk_Kraftsensor",
        "Amazon_Kamera-Sony-Alpha",
        "Lego_EV3-Bundle",
        "Amazon_Grill",
        "HBM_Kraftsensor",
        "HBM_Messverstärker",
        "Kistler_Beschleunigungssensor",
        "Kuka_Force-Torque",
        "Voelkner_PoE-Switch",
        "Perschmann_Säulenbormaschine",
        "PI_Piezoaktor-und-Controller",
        "MCC_Massendurchflussregler",
        "HBM_Zug-Druckaufnehmer-1kN",
        "3D Scanner",
        "Reichelt_3D-Drucker-Ultimaker-2-Extended",
        "Smart-Robotics_UniversalRobot_UR5",
        "Leister_Lufterhitzer",
        "Wingold_Thermografiekamera",
        "Präzisionsmontagezelle",
        "Distrelec (Antriebsverstärker)",
        "HBM_QuantumX",
        "Faro_Präzisionsmessgerät",
        "Kaffeeberater_Kaffeemaschine",
        "VisaRaatz_Apple_IPadPro",
        "Datron_M8-Cube",
        "Maka_Dosiergerät-Handgerät-PM",
        "Festo_Servopneumatik",
        "Mahr_Messmikroskop",
        "Memmert_Laborofen-Klimaraum",
        "Newport_Motorisierung_Goniometer",
        "Weidinger_Ionisiergerät-Topgun",
        "Rasche24_Bandsäge",
        "Gestigkeit_Präzisionsheizplatte",
        "IDS_Kamera-Stereomikroskop",
        "Notebooksbillger_Kühlschrank",
        "Zeiss_Stereomikroskop",
        "MM-Engineering_Förderband_Flexpicker",
        "National-Instruments_DAQ",
        "KUKA_Agilus KR6",
        "KUKA_KR60-3",
        "Weidinger_2K-Dosierer",
        "Westermann_Lego_EV3-Bundle",
        "Datron_Schraubstock",
        "MM-Engineering_RoMo-Bandförderer",
        "Maxon_BioRob-Motor",
        "Newport_Isolator-System",
        "Konfokal-chromatisches Sensorsystem (micro-epsilon)",
        "MM-Engineering_Motorpositioniertisch-Aero",
        "Laserscanner",
        "MIR-200",
        "Panda",
        "Pilz_Lichtgitter",
        "Schunk_Co-act-Greifer",
        "Amazon_Surface_Pro",
        "KUKA_iiwa",
        "Schmalz_VEE_Starterset",
        "Keyence_Agilista_3D-Drucker",
        "Omega_Temperaturlogger",
        "PI_Piezoverstärker",
        "PI_Schnittstellenmodul",
        "Siemens_Logo",
        "Siemens_Motor_Versuchsstand-SFB-871",
        "Siemens_S7-1516",
        "Conrad_60V-Labornetzgerät_Aim-TTi-CPX400DP",
        "Notebooksbilliger_Notebook-Annika",
        "Notebooksbilliger_Notebook-Richard",
        "Projektor-AG_Beamer",
        "Teufel_Box",
        "WKM_KTB-Tiefkühltruhe",
        "Notebooksbilliger_Notebook-Ditzia",
        "Siemens_SPS",
        "Alternate_Mini-PC-MiR",
        "Thode-Werkzeuge_Metallbandsäge",
        "Alternate_Razer-Blade",
        "Cyberport_iPad-PM",
        "Amazon_LA-3D-Drucker",
        "Raatz_Apple_Diensthandy-Annika",
        "Notebooksbilliger_Notebook-Lachmayer",
        "Alternate_Hiwi-Rechner",
        "Notebook-Gerland",
        "GS-Glovebox",
        "Microsoft_Hololens 2",
        "ICS_MiR-100",
        "KEYENCE_2D-Laserscanner",
        "KEYENCE_Controller-Laserscanner",
        "OLYMPUS_Mikroskop-PhxD",
        "Beckhoff_IPC",
        "Conrad_ASR-2050_Funktionsgenerator-bis-350V-AC-Netzteil",
        "Siemens_S7-1200",
        "Franka_Emika",
        "Alternate_Notebook-Klingeberg",
        "Baumer_Hochgeschwindigkeitskamera",
        "CSL_Bildverarbeitungsrechner-PM-Computer",
        "Hönle_Bluepoint-LED-eco",
        "Foto-Köster_Videokamera Panasonic X1E",
        "Dell_Notebook-Lurz",
        "Dell_Notebook-Terei",
        "Generation-Robots_Boston-Dynamics_Spot",
        "Conrad_Ultimaker-S5",
        "Source-IT_ROS-PC",
        "Apple_iPad-Pro-Raatz",
        "Alternate_Keyence_Bildverarbeitung-PC",
        "Dell_Notebook-Binnemann",
        "Igus_5-DoF-Robot",
        "Lorenscheit_UR16e",
        "CSL_Studi-Rechner-MLL",
        "dSpace_PhoenixD",
        "Dell_Server",
        "MyBotShop_Marvelmind-Beacon",
        "BZT-CNC_Tischfräsmaschine",
        "ROS-Simulations-PC",
        "UR16e",
        "Sony Alpha 7 iV",
        "Großgerät Multirobotersystem SCALE",
        "OnRobot Greifer",
        "Flux Hexa Laser",
        "Kontaktwinkelmessgerät",
        "Mafu-Mover-System",
        "Notebook Raatz",
        "Notebook Sourkounis",
        "Optisches Tracking",
        "Hochdruckreiniger Nilfiks",
        "Laser Dioden Controller",
        "Leitstand VW",
        "Schunk Kraftsensor 17 Nano",
        "SmarAct Parallelgreifer",
        "Stepper-Achse",
        "UV-Taschenlampe",
        "Funk Not-Halt",
        "Klebstoffdispenssystem",
        "Leitstand SCALE",
        "Spot-Controller",
        "PM_Toolchanger",
        "Labormultimeter DMM 6050",
        "Hönle-UV-Flächenstrahler",
        "Beckhoff SPS - SFB 1153 - C07",
        "ROSBot 2 Pro",
        "Drucker Carmen",
        "Notebook Kleinschmidt",
        "Workstation Tschöke",
        "Staubsauger SCALE",
        "Notebook Ince",
        "Notebook Wendorff",
        "OpBox Ultraschall",
        "Klebstoffdosiersystem 2K",
        "Notebook Westermann",
        "Computer-Versuchsfeld",
        "HyPo Lasertriangulationssensor",
        "HyPo Wärmebildkamera",
        "Laptop Peters",
        "iPhone SE",
        "SPP 2433 Drohne",
        "SPP 2100 Kamerasystem",
        "Formlabs Form 4 SLA-Drucker",
        "Industrie-PC HyPo",
        "Einbauschrauber Zukunftslabor",
        "Beckhoff IPC C6043 ML BiBaZu",
        "Prusa Core One L",
        "Raatz Surface",
        "Raatz Iphone",
    ]
)

# Allgemeine Arbeitsplatzrechner, Tablets, Server und Smartphones gehören nicht
# in das Geräteinventar.
# Spezialisierte Industrie-, Steuerungs- und Bildverarbeitungsrechner bleiben dagegen
# als Forschungsgeräte erhalten.
EXCLUDED_IT_DEVICE_NAMES = frozenset(
    {
        "Alternate_Hiwi-Rechner",
        "Alternate_Mini-PC-MiR",
        "Alternate_Notebook-Klingeberg",
        "Alternate_Razer-Blade",
        "Amazon_Surface_Pro",
        "Apple_iPad-Pro-Raatz",
        "CSL_Studi-Rechner-MLL",
        "Computer-Versuchsfeld",
        "Cyberport_iPad-PM",
        "Dell_Server",
        "Dell_Notebook-Binnemann",
        "Dell_Notebook-Lurz",
        "Dell_Notebook-Terei",
        "Laptop Peters",
        "Notebook Ince",
        "Notebook Kleinschmidt",
        "Notebook Raatz",
        "Notebook Sourkounis",
        "Notebook Wendorff",
        "Notebook Westermann",
        "Notebook-Gerland",
        "Notebooksbilliger_Notebook-Annika",
        "Notebooksbilliger_Notebook-Ditzia",
        "Notebooksbilliger_Notebook-Lachmayer",
        "Notebooksbilliger_Notebook-Richard",
        "ROS-Simulations-PC",
        "Raatz Iphone",
        "Raatz Surface",
        "Raatz_Apple_Diensthandy-Annika",
        "Source-IT_ROS-PC",
        "VisaRaatz_Apple_IPadPro",
        "Workstation Tschöke",
        "iPhone SE",
    }
)

CLEAR_DEVICE_NAMES -= EXCLUDED_IT_DEVICE_NAMES


# Nur technische Produktbezeichnungen ohne Personen-, Raum- oder Projektbezug dürfen
# an die öffentliche Recherche gehen. Fehlt ein eindeutiger Typ, bleibt die Recherche
# bewusst auf „Typ nicht eindeutig“.
RESEARCH_HINTS = {
    "Stäubli_TX200": "Stäubli TX200 industrial robot",
    "Lego_EV3-Bundle": "LEGO Mindstorms EV3",
    "Reichelt_3D-Drucker-Ultimaker-2-Extended": "Ultimaker 2 Extended",
    "Smart-Robotics_UniversalRobot_UR5": "Universal Robots UR5",
    "HBM_QuantumX": "HBM QuantumX data acquisition system",
    "VisaRaatz_Apple_IPadPro": "Apple iPad Pro",
    "Datron_M8-Cube": "DATRON M8Cube CNC",
    "KUKA_KR60-3": "KUKA KR 60-3 industrial robot",
    "Westermann_Lego_EV3-Bundle": "LEGO Education MINDSTORMS EV3 manufacturer",
    "MIR-200": "site:mobile-industrial-robots.com MiR200 specifications",
    "Panda": "Franka Emika Panda official technical data",
    "Amazon_Surface_Pro": "Microsoft Surface Pro",
    "KUKA_iiwa": "KUKA LBR iiwa",
    "Keyence_Agilista_3D-Drucker": "Keyence AGILISTA 3200W",
    "Siemens_Logo": "Siemens LOGO PLC",
    "Siemens_S7-1516": "Siemens SIMATIC S7-1516",
    "Conrad_60V-Labornetzgerät_Aim-TTi-CPX400DP": "Aim-TTi CPX400DP",
    "Alternate_Razer-Blade": "Razer Blade laptop",
    "Microsoft_Hololens 2": "Microsoft HoloLens 2",
    "ICS_MiR-100": "Mobile Industrial Robots MiR100",
    "Conrad_ASR-2050_Funktionsgenerator-bis-350V-AC-Netzteil": "GW Instek ASR-2050",
    "Siemens_S7-1200": "Siemens SIMATIC S7-1200",
    "Franka_Emika": "Franka Emika Panda official technical data",
    "Generation-Robots_Boston-Dynamics_Spot": "Boston Dynamics Spot",
    "Conrad_Ultimaker-S5": "Ultimaker S5",
    "Igus_5-DoF-Robot": "igus 5 DoF robot",
    "Lorenscheit_UR16e": "Universal Robots UR16e",
    "dSpace_PhoenixD": "dSPACE PhoenixD",
    "MyBotShop_Marvelmind-Beacon": "Marvelmind Beacon",
    "Sony Alpha 7 iV": "Sony Alpha 7 IV",
    "UR16e": "Universal Robots UR16e",
    "Flux Hexa Laser": "FLUX HEXA laser cutter",
    "Schunk Kraftsensor 17 Nano": "SCHUNK FTNANO 17 force torque sensor",
    "Labormultimeter DMM 6050": "DMM 6050 bench multimeter",
    "ROSBot 2 Pro": "Husarion ROSbot 2 PRO",
    "Formlabs Form 4 SLA-Drucker": "Formlabs Form 4",
    "Beckhoff IPC C6043 ML BiBaZu": "Beckhoff C6043 industrial PC",
    "Prusa Core One L": "Prusa CORE One L",
}


MANUFACTURER_HINTS = {
    "Stäubli_TX200": "Stäubli",
    "KUKA_AgilusKR6": "KUKA",
    "Schunk_Kraftsensor": "SCHUNK",
    "Amazon_Kamera-Sony-Alpha": "Sony",
    "HBM_Kraftsensor": "HBM",
    "HBM_Messverstärker": "HBM",
    "Kistler_Beschleunigungssensor": "Kistler",
    "Kuka_Force-Torque": "KUKA",
    "PI_Piezoaktor-und-Controller": "PI",
    "HBM_Zug-Druckaufnehmer-1kN": "HBM",
    "Reichelt_3D-Drucker-Ultimaker-2-Extended": "Ultimaker",
    "Smart-Robotics_UniversalRobot_UR5": "Universal Robots",
    "Leister_Lufterhitzer": "Leister",
    "HBM_QuantumX": "HBM",
    "Faro_Präzisionsmessgerät": "FARO",
    "VisaRaatz_Apple_IPadPro": "Apple",
    "Datron_M8-Cube": "DATRON",
    "Festo_Servopneumatik": "Festo",
    "Mahr_Messmikroskop": "Mahr",
    "Memmert_Laborofen-Klimaraum": "Memmert",
    "Newport_Motorisierung_Goniometer": "Newport",
    "Zeiss_Stereomikroskop": "ZEISS",
    "National-Instruments_DAQ": "National Instruments",
    "KUKA_KR60-3": "KUKA",
    "KUKA_Agilus KR6": "KUKA",
    "Maxon_BioRob-Motor": "maxon",
    "Konfokal-chromatisches Sensorsystem (micro-epsilon)": "Micro-Epsilon",
    "MIR-200": "Mobile Industrial Robots",
    "Panda": "Franka Emika",
    "Pilz_Lichtgitter": "Pilz",
    "Schunk_Co-act-Greifer": "SCHUNK",
    "Amazon_Surface_Pro": "Microsoft",
    "KUKA_iiwa": "KUKA",
    "Schmalz_VEE_Starterset": "Schmalz",
    "Keyence_Agilista_3D-Drucker": "KEYENCE",
    "Omega_Temperaturlogger": "OMEGA",
    "PI_Piezoverstärker": "PI",
    "PI_Schnittstellenmodul": "PI",
    "Siemens_Logo": "Siemens",
    "Siemens_Motor_Versuchsstand-SFB-871": "Siemens",
    "Siemens_S7-1516": "Siemens",
    "Conrad_60V-Labornetzgerät_Aim-TTi-CPX400DP": "Aim-TTi",
    "Teufel_Box": "Teufel",
    "Siemens_SPS": "Siemens",
    "Microsoft_Hololens 2": "Microsoft",
    "ICS_MiR-100": "Mobile Industrial Robots",
    "KEYENCE_2D-Laserscanner": "KEYENCE",
    "KEYENCE_Controller-Laserscanner": "KEYENCE",
    "OLYMPUS_Mikroskop-PhxD": "Olympus",
    "Beckhoff_IPC": "Beckhoff",
    "Siemens_S7-1200": "Siemens",
    "Franka_Emika": "Franka Emika",
    "Baumer_Hochgeschwindigkeitskamera": "Baumer",
    "Hönle_Bluepoint-LED-eco": "Hönle",
    "Dell_Notebook-Lurz": "Dell",
    "Dell_Notebook-Terei": "Dell",
    "Generation-Robots_Boston-Dynamics_Spot": "Boston Dynamics",
    "Conrad_Ultimaker-S5": "Ultimaker",
    "Apple_iPad-Pro-Raatz": "Apple",
    "Dell_Notebook-Binnemann": "Dell",
    "Igus_5-DoF-Robot": "igus",
    "Lorenscheit_UR16e": "Universal Robots",
    "dSpace_PhoenixD": "dSPACE",
    "Dell_Server": "Dell",
    "Sony Alpha 7 iV": "Sony",
    "UR16e": "Universal Robots",
    "OnRobot Greifer": "OnRobot",
    "Flux Hexa Laser": "FLUX",
    "Schunk Kraftsensor 17 Nano": "SCHUNK",
    "SmarAct Parallelgreifer": "SmarAct",
    "Hönle-UV-Flächenstrahler": "Hönle",
    "ROSBot 2 Pro": "Husarion",
    "HyPo Lasertriangulationssensor": "Cognex",
    "Formlabs Form 4 SLA-Drucker": "Formlabs",
    "Beckhoff IPC C6043 ML BiBaZu": "Beckhoff",
    "Prusa Core One L": "Prusa Research",
}


MODEL_HINTS = {
    "Stäubli_TX200": "TX200",
    "Lego_EV3-Bundle": "Mindstorms EV3",
    "Reichelt_3D-Drucker-Ultimaker-2-Extended": "Ultimaker 2 Extended",
    "Smart-Robotics_UniversalRobot_UR5": "UR5",
    "HBM_QuantumX": "QuantumX",
    "VisaRaatz_Apple_IPadPro": "iPad Pro",
    "Datron_M8-Cube": "M8Cube",
    "KUKA_KR60-3": "KR 60-3",
    "Westermann_Lego_EV3-Bundle": "Mindstorms EV3",
    "MIR-200": "MiR200",
    "Panda": "Panda",
    "Amazon_Surface_Pro": "Surface Pro",
    "KUKA_iiwa": "LBR iiwa",
    "Keyence_Agilista_3D-Drucker": "AGILISTA 3200W",
    "Siemens_Logo": "LOGO!",
    "Siemens_S7-1516": "SIMATIC S7-1516",
    "Conrad_60V-Labornetzgerät_Aim-TTi-CPX400DP": "CPX400DP",
    "Alternate_Razer-Blade": "Razer Blade",
    "Microsoft_Hololens 2": "HoloLens 2",
    "ICS_MiR-100": "MiR100",
    "Conrad_ASR-2050_Funktionsgenerator-bis-350V-AC-Netzteil": "ASR-2050",
    "Siemens_S7-1200": "SIMATIC S7-1200",
    "Generation-Robots_Boston-Dynamics_Spot": "Spot",
    "Conrad_Ultimaker-S5": "Ultimaker S5",
    "dSpace_PhoenixD": "PhoenixD",
    "MyBotShop_Marvelmind-Beacon": "Marvelmind Beacon",
    "Lorenscheit_UR16e": "UR16e",
    "Sony Alpha 7 iV": "Alpha 7 IV",
    "UR16e": "UR16e",
    "Flux Hexa Laser": "HEXA",
    "Schunk Kraftsensor 17 Nano": "FTNANO 17",
    "Labormultimeter DMM 6050": "DMM 6050",
    "ROSBot 2 Pro": "ROSbot 2 PRO",
    "Formlabs Form 4 SLA-Drucker": "Form 4",
    "Beckhoff IPC C6043 ML BiBaZu": "C6043",
    "Prusa Core One L": "CORE One L",
}


def clean_device_name(name):
    return re.sub(r"\s+", " ", name.replace("_", " ")).strip()


def category_name(name, tool_type=""):
    lower = name.lower()
    if any(word in lower for word in ("sensor", "kamera", "scanner", "lichtgitter", "tracking")):
        return "Sensoren"
    if any(word in lower for word in ("robot", "kuka", "stäubli", "ur5", "ur16", "mir-", "spot")):
        return "Roboter"
    if any(
        word in lower
        for word in (
            "pc",
            "computer",
            "notebook",
            "laptop",
            "ipad",
            "iphone",
            "surface",
            "server",
            "hololens",
            "drucker",
        )
    ):
        return "IT / Elektronik"
    if any(
        word in lower
        for word in ("säge", "bohrmaschine", "schraubstock", "schrauber", "toolchanger", "hochdruckreiniger")
    ):
        return "Werkzeuge"
    if tool_type == "actuator" or any(word in lower for word in ("motor", "aktor", "greifer", "achse")):
        return "Aktoren"
    if any(
        word in lower
        for word in (
            "multimeter",
            "oszilloskop",
            "netzgerät",
            "mess",
            "logger",
            "daq",
            "controller",
            "verstärker",
        )
    ):
        return "Mess- und Prüfgeräte"
    if any(
        word in lower for word in ("cnc", "ofen", "glovebox", "frä", "zelle", "förderband", "dosier", "laser")
    ):
        return "Maschinen und Anlagen"
    return "Sonstiges"
