# Generated by Django 5.2.17 on 2026-09-23 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis (voraussichtliche Rückgabe)')),
                ('status', models.CharField(choices=[('requested', 'Angefragt'), ('reserved', 'Reserviert'), ('active', 'Ausgeliehen'), ('returned', 'Zurückgegeben'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert'), ('expired', 'Verfallen')], db_index=True, max_length=20, verbose_name='Status')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Zweck / Projekt')),
                ('usage_location', models.CharField(blank=True, max_length=200, verbose_name='Einsatzort')),
                ('request_message', models.TextField(blank=True, verbose_name='Nachricht an Verantwortliche/n')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Kommentar zur Entscheidung')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Entschieden am')),
                ('requested_end_date', models.DateField(blank=True, null=True, verbose_name='Beantragtes neues Enddatum')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Entnommen am')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Zurückgegeben am')),
                ('return_note', models.TextField(blank=True, verbose_name='Rückgabenotiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Ausleiher/in')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eingetragen von')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Entschieden von')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='inventory.item', verbose_name='Gerät')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Rückgabe gebucht von')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('due_tomorrow', 'Rückgabe morgen fällig'), ('overdue', 'Überfällig'), ('starts_today', 'Reservierung beginnt heute'), ('pending_request', 'Offene Anfrage')], max_length=20, verbose_name='Art')),
                ('sent_on', models.DateField(verbose_name='Versendet am')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.booking')),
            ],
            options={
                'verbose_name': 'Erinnerung',
                'verbose_name_plural': 'Erinnerungen',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['item', 'status', 'start_date', 'end_date'], name='loans_booki_item_id_1120bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='booking_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('booking', 'kind', 'sent_on'), name='unique_reminder_per_day'),
        ),
    ]
