# Generated by Django 5.2.17 on 2026-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='kind',
            field=models.CharField(choices=[('starts_soon', 'Reservierung beginnt'), ('due_soon', 'Rückgabe fällig'), ('overdue', 'Überfällig (an Ausleiher/in)'), ('owner_overdue', 'Überfällig (an Verantwortliche/n)'), ('pending_request', 'Unbeantwortete Anfrage')], max_length=20, verbose_name='Art'),
        ),
    ]
