# Generated by Django 5.2.17 on 2026-09-22 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100, verbose_name='Eigenschaft')),
                ('value_text', models.CharField(max_length=200, verbose_name='Originalangabe')),
                ('min_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Minimum')),
                ('max_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Maximum')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='Einheit')),
                ('source_url', models.URLField(max_length=500, verbose_name='Quellenlink')),
                ('source_title', models.CharField(blank=True, max_length=200, verbose_name='Quellentitel')),
                ('source_kind', models.CharField(choices=[('manufacturer', 'Hersteller'), ('dealer', 'Händler'), ('document', 'Inventardokument')], max_length=20, verbose_name='Quellenart')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Geprüft am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='inventory.item')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geprüfter Kennwert',
                'verbose_name_plural': 'Geprüfte Kennwerte',
                'ordering': ['property_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100, verbose_name='Eigenschaft')),
                ('value_text', models.CharField(max_length=200, verbose_name='Originalangabe')),
                ('min_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Minimum')),
                ('max_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Maximum')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='Einheit')),
                ('source_url', models.URLField(max_length=500, verbose_name='Quellenlink')),
                ('source_title', models.CharField(blank=True, max_length=200, verbose_name='Quellentitel')),
                ('source_kind', models.CharField(choices=[('manufacturer', 'Hersteller'), ('dealer', 'Händler'), ('document', 'Inventardokument')], max_length=20, verbose_name='Quellenart')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am')),
                ('status', models.CharField(choices=[('pending', 'Zur Prüfung'), ('approved', 'Übernommen'), ('rejected', 'Verworfen')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_proposals', to='inventory.item')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kennwertvorschlag',
                'verbose_name_plural': 'Kennwertvorschläge',
                'ordering': ['-created_at'],
            },
        ),
    ]
