# Generated by Django 5.2.17 on 2026-09-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_condition'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.item', verbose_name='Inventargerät'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='research_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Recherchedaten'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='research_source_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quellentitel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='research_source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Recherchequelle'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='research_status',
            field=models.CharField(choices=[('not_started', 'Nicht recherchiert'), ('researched', 'Recherche vorhanden'), ('ambiguous', 'Typ nicht eindeutig'), ('failed', 'Recherche fehlgeschlagen')], default='not_started', max_length=20, verbose_name='Recherchestatus'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='research_summary',
            field=models.TextField(blank=True, verbose_name='Rechercheergebnis'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='researched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recherchiert am'),
        ),
    ]
